version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo_db
    environment:
      - db_host=mongo_db
      - db_user=y1balaev
      - db_pass=rVsueR6Q4UYwG6pb

    ports:
      - 3000:3000
    volumes:
      - ./build:/build

  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: y1balaev
      MONGO_INITDB_ROOT_PASSWORD: rVsueR6Q4UYwG6pb
    volumes:
      - ./mongo_db:/mongo_db