version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      MONGO_USERNAME: y1balaev
      MONGO_PASSWORD: rVsueR6Q4UYwG6pb
      MONGO_HOSTNAME: mongo_db
      MONGO_DB: dance_connect
    ports:
      - "27017:27017"
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command:  yarn start

  mongo_db:
    image: mongo:4.1.8-xenial
    container_name: mongo_db
    restart: unless-stopped
    environment:
      MONGO_USERNAME: y1balaev
      MONGO_PASSWORD: rVsueR6Q4UYwG6pb
    volumes:     
      - mongo_data:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  node_modules:  