version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      MONGO_USERNAME: y1balaev
      MONGO_PASSWORD: rVsueR6Q4UYwG6pb
      MONGO_HOSTNAME: db
      MONGO_DB: dance_connect
    ports:
      - "3000:3000"
      - "27017:27017"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command:  yarn start

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    environment:
      MONGO_USERNAME: y1balaev
      MONGO_PASSWORD: rVsueR6Q4UYwG6pb
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  