version: "3.2"
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    build:
      context: ${PWD}/path/to/Dockerfile
    volumes:
     - $PWD/mongo_db:/data/db

    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: y1balaev
      MONGO_INITDB_ROOT_PASSWORD: rVsueR6Q4UYwG6pb
