version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      - db_host=mongo_db
      - db_user=y1balaev
      - db_pass=rVsueR6Q4UYwG6pb
      # MONGO_DB: dance_connect
    links:
      - mongo_db
    ports:
      - "27017:27017"
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command:  yarn start

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: dc
      MONGO_INITDB_ROOT_USERNAME: y1balaev
      MONGO_INITDB_ROOT_PASSWORD: rVsueR6Q4UYwG6pb
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo_data:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  node_modules: