version: '3.7'
services:
  dance-connect-db:
    image: mongo
    restart: always
    container_name: dance-connect-db
    ports:
      - 27017:27017 
    volumes:
      - dance-connect-db:/data/db
    networks: 
      - dance-connect-network
  dance-connect-app:
    image: dance-connect-app:prod
    build: 
      context: .
      target: prod
    container_name: dance-connect-app
    restart: always
    volumes: 
      - .:/app
    ports:
      - "27017:27017"
      - "3000:3000"
    depends_on:
      - dance-connect-db
    environment:
      - MONGODB_URI=mongodb://dance-connect-db/dance-connect-db
    networks: 
      - dance-connect-network
volumes: 
  dance-connect-db:
    name: dance-connect-db
networks: 
  dance-connect-network:
    name: dance-connect-network
